GustavNordstrom/DD2480Decide

- src/main/java/com/dd2480/CMV/CMV.java
- src/main/java/com/dd2480/PUM/PUMManager.java
- src/main/java/com/dd2480/PUM/impl/PUMManagerImpl.java
- src/test/java/com/dd2480/CMV/CMVTest.java
- src/test/java/com/dd2480/PUM/impl/PUMManagerImplTest.java
#8 
#6 
This way it's easier to create immutable CMV object in a flexible manner.
> Add a object builder for class CMV

- src/main/java/com/dd2480/CMV/impl/ConditionTwo.java
- src/test/java/com/dd2480/CMV/impl/ConditionTwoTest.java
There exists at least one set of three consecutive data points which form an angle such that:
angle < (PI−EPSILON)
or
angle > (PI+EPSILON)
The second of the three consecutive points is always the vertex of the angle. If either the first point or the last point (or both) coincides with the vertex, the angle is undefined and the LIC is not satisfied by those three points.
(0 $\leq$ EPSILON < PI)
> Implement condition two and its test code.

- src/main/java/com/dd2480/CMV/impl/ConditionThree.java
- src/test/java/com/dd2480/CMV/impl/ConditionThreeTest.java
There exists at least one set of three consecutive data points that are the vertices of a triangle with area greater than AREA1.
(0 $\leq$ AREA1)
> Implement the 3rd condition and its test code.

- src/main/java/com/dd2480/common/LCM.java
- src/test/java/com/dd2480/common/LCMTest.java
I implemented an object builder for this class to simplify testing.
> Add object builder for LCM

- pom.xml
- src/main/java/com/dd2480/CMV/ConditionManager.java
- src/main/java/com/dd2480/CMV/impl/ConditionManagerImpl.java
- src/test/java/com/dd2480/CMV/impl/ConditionManagerImplTest.java
We can add now unlimited classes implementing Condion interface.
#6
> Add condtion class scanner

- src/main/java/com/dd2480/CMV/impl/ConditionFive.java
- src/test/java/com/dd2480/CMV/impl/ConditionFiveTest.java
There exists at least one set of two consecutive data points, (X[i],Y[i]) and (X[j],Y[j]), such that X[j] - X[i] < 0. (where i = j-1)
> The 5th condition implementation and its test.

- src/main/java/com/dd2480/CMV/impl/ConditionEleven.java
- src/main/java/com/dd2480/common/Parameters.java
- src/test/java/com/dd2480/CMV/impl/ConditionElevenTest.java
There exists at least one set of two data points, (X[i],Y[i]) and (X[j],Y[j]), separated by exactly G_PTS consecutive intervening points, such that X[j] - X[i] < 0. (where i < j ) The condition is not met when NUMPOINTS < 3.
1 $\leq$ G_PTS $\leq$ NUMPOINTS−2
Add an variable **_G_PTS_** and one interface to **_Parameters.java_**, **_getGPTS()_**, which return **_G_PTS_**.
> The 11th condition implementation.

- src/main/java/com/dd2480/CMV/impl/ConditionEight.java
- src/main/java/com/dd2480/CMV/impl/ConditionEleven.java
- src/main/java/com/dd2480/CMV/impl/ConditionFive.java
- src/main/java/com/dd2480/CMV/impl/ConditionFour.java
- src/main/java/com/dd2480/CMV/impl/ConditionNine.java
- src/main/java/com/dd2480/CMV/impl/ConditionSeven.java
- src/main/java/com/dd2480/CMV/impl/ConditionSix.java
- src/main/java/com/dd2480/CMV/impl/ConditionTen.java
- src/main/java/com/dd2480/common/Parameters.java
- src/test/java/com/dd2480/CMV/impl/ConditionEightTest.java
- src/test/java/com/dd2480/CMV/impl/ConditionElevenTest.java
- src/test/java/com/dd2480/CMV/impl/ConditionFiveTest.java
- src/test/java/com/dd2480/CMV/impl/ConditionFourTest.java
- src/test/java/com/dd2480/CMV/impl/ConditionNineTest.java
- src/test/java/com/dd2480/CMV/impl/ConditionSevenTest.java
- src/test/java/com/dd2480/CMV/impl/ConditionSixTest.java
- src/test/java/com/dd2480/CMV/impl/ConditionTenTest.java
This Pull Request implements conditions 4 to 11 as specified in the project requirements and adds corresponding interfaces to the codebase. Additionally, commit messages were updated for better traceability and compliance with collaboration standards. The revised commit messages now follow conventional commit guidelines and reference the appropriate issues.
- **Condition 4**: Added `getQPTS()` and `getQUAD()` interfaces (#19).
- **Condition 5**: Implemented with `getPTS()` interface (#20).
- **Condition 6**: Added `getDIST()` and `getNPTS()` interfaces (#21).
- **Condition 7**: Added `getKPTS()` interface (#22).
- **Condition 8**: Added `getAPTS()` and `getBPTS()` interfaces (#23).
- **Condition 9**: Added `getCPTS()` and `getDPTS()` interfaces (#24).
- **Condition 10**: Added `getEPTS()` …
> feat: Implement conditions 4 to 11 and add corresponding interfaces

- src/main/java/com/dd2480/FUV/impl/FUVManagerImpl.java
- src/main/java/com/dd2480/PUM/PUM.java
- src/test/java/com/dd2480/FUV/impl/FUVManagerImplTest.java
> Add a test for class  FUVManager

- src/main/java/com/dd2480/App.java
- src/main/java/com/dd2480/inputoutput/InputHandler.java
- src/main/java/com/dd2480/inputoutput/OutputHandler.java
> Add input and output interface

- README.md
Add contribution statement of Wen Biming
]
#72
> doc. Add contribution statement of Wen Biming (#72)

- README.md
- Adds contribution statement for Gustav Nordström
Please list any issues related to this pull request. You can link issues by using `#<issue-number>`.
- #72
> doc: add contribution statement of Gustav Nordström

- README.md
Add contribution section for Xu Zuo.
#72
> docs: fill out contribution section (#72)

- README.md
- Contribution statement for Gustav Wallin
- #72
> doc: contribution Gustav Wallin (#72)

- README.md
Also include information how to run the program in the readme file
- Could be useful
- Desribes requirements, and commands for running and testing
- Closes #81 
Any suggestions for rephrasing etc is welcomed
> doc: add info in readme on how to run the program (#81)

- src/main/java/com/dd2480/CMV/impl/ConditionEight.java
- src/main/java/com/dd2480/CMV/impl/ConditionFour.java
- src/main/java/com/dd2480/CMV/impl/ConditionFourteen.java
- src/main/java/com/dd2480/CMV/impl/ConditionNine.java
- src/main/java/com/dd2480/CMV/impl/ConditionOne.java
- src/main/java/com/dd2480/CMV/impl/ConditionSeven.java
- src/main/java/com/dd2480/CMV/impl/ConditionSix.java
- src/main/java/com/dd2480/CMV/impl/ConditionTen.java
- src/main/java/com/dd2480/CMV/impl/ConditionThirteen.java
- src/main/java/com/dd2480/CMV/impl/ConditionThree.java
- src/main/java/com/dd2480/CMV/impl/ConditionTwelve.java
- src/main/java/com/dd2480/CMV/impl/ConditionTwo.java
- src/main/java/com/dd2480/CMV/impl/ConditionZero.java
- src/main/java/com/dd2480/common/CalculationUtils.java
As included in the lab specification, this doubleCompare method is implemented in the same way.
- Good practice to use proper double compare
- Implemented function in calculationUtils.java file
- refactored LICs to use this method where needed
- Also found a bug in lic 2 where points were not accurately compared
- Closes #57 
The code could be made more readable but i think it is fine.
> Feat: implement doublecompare utility function (#57)

- src/test/java/com/dd2480/CMV/impl/ConditionEightTest.java
- src/test/java/com/dd2480/CMV/impl/ConditionZeroTest.java
- Should be three test per function
- therefore added a negative test for those two lic's
- [x My code follows the project's coding style guidelines
- Closes #61
> feat: add additional test for LIC0 and LIC8 functions (#61)

- README.md
Add the essence paragraph in readme.md
> doc: add essence paragraph in README

- src/main/java/com/dd2480/App.java
- src/main/java/com/dd2480/inputoutput/OutputFormatter.java
- src/test/java/com/dd2480/AppTest.java
- src/test/java/com/dd2480/inputoutput/OutputFormatterTest.java
Add a class OutputFormatter.
Please describe the testing that has been done on the changes. Include the testing environment, and any relevant details or configurations.
#85
> fix: Implement clearer output (#85)

- README.md
Update contribution section for Xu Zuo's contribution in this project.
#86
> docs: Update README.md for Xu Zuo in the contribution section (#86)

- src/main/java/com/dd2480/CMV/CMV.java
- src/main/java/com/dd2480/FUV/FUV.java
- src/main/java/com/dd2480/FUV/FUVManager.java
- src/main/java/com/dd2480/FUV/impl/FUVManagerImpl.java
- src/main/java/com/dd2480/PUM/PUM.java
- src/main/java/com/dd2480/PUM/PUMManager.java
- src/main/java/com/dd2480/PUM/impl/PUMManagerImpl.java
- src/main/java/com/dd2480/common/LCM.java
- src/main/java/com/dd2480/common/PUV.java
- src/main/java/com/dd2480/common/Parameters.java
- src/main/java/com/dd2480/common/Point.java
- src/main/java/com/dd2480/inputoutput/InputData.java
- src/main/java/com/dd2480/inputoutput/InputHandler.java
- src/main/java/com/dd2480/inputoutput/OutputFormatter.java
- src/main/java/com/dd2480/inputoutput/impl/InputHandlerImpl.java
- src/main/java/com/dd2480/inputoutput/impl/OutputHandlerImpl.java
add comments for modules CMV, FUV, PUM, inputoutput 
#87 
- Closes #<issue-number> (if applicable)
> doc: add comments for CMV, FUV, PUM, inputoutput (#87)

- src/test/java/com/dd2480/AppTest.java
Update the comments for each test case in _AppTest.java_.
#87 
Feel free to add additional and necessary comments to the same file. And please add necessary comments to the files which remains to be updated and close the related issue. Thanks.
> docs: Update comments in AppTest.java (#87)

- README.md
Provide the detailed explanation of contribution statement of Wen Biming.
#86
> doc: update statement of contribution (#86)

- README.md
Updated contribution statement 
- #88
> doc: final contribution statement Gustav Wallin (#88)
